# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 05:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belleza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Recreacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto1', models.ImageField(upload_to='img/servicio')),
                ('foto2', models.ImageField(upload_to='img/servicio')),
                ('foto3', models.ImageField(upload_to='img/servicio')),
                ('foto4', models.ImageField(upload_to='img/servicio')),
                ('foto5', models.ImageField(upload_to='img/servicio')),
                ('titulo', models.CharField(max_length=100)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
